#!/usr/bin/env bash
# 把 manifest + rules 摘要烘焙进桥接层 GENERATED 区段
set -euo pipefail

command -v yq >/dev/null 2>&1 || { echo "❌ 需要 yq (mikefarah/yq v4+)。安装：brew install yq / apt install yq"; exit 2; }

HARNESS_ROOT="${HARNESS_ROOT:-.harness}"
START_MARKER="<!-- HARNESS-GENERATED-START -->"
END_MARKER="<!-- HARNESS-GENERATED-END -->"

generate_summary() {
  local manifest="$1"
  local prefix="$2"   # "" for local, "parent: " for inherited

  yq e '.cognition.loadOrder[]' "$manifest" | while read -r rel; do
    [ -z "$rel" ] && continue
    local f="$(dirname "$manifest")/$rel"
    [ -f "$f" ] || continue

    # 提取 severity 与首段
    local sev title hook
    sev=$(awk '/^severity:/ {print $2; exit}' "$f")
    title=$(awk '/^# / {print substr($0, 3); exit}' "$f")
    hook=$(awk '
      BEGIN {capture=0}
      /^---$/ {fm=!fm; next}
      fm {next}
      /^# / {capture=1; next}
      capture && /^[^#]/ && NF>0 {print; exit}
    ' "$f")

    case "$sev" in
      critical) emoji="🔴" ;;
      high)     emoji="🟠" ;;
      medium)   emoji="🟡" ;;
      *)        emoji="⚪" ;;
    esac

    echo "- ${emoji} **${prefix}${title}** (\`${rel}\`) — ${hook:0:120}"
  done
}

bake_bridge() {
  local bridge_file="$1"
  [ -f "$bridge_file" ] || { echo "skip $bridge_file (not found)"; return; }

  local tmp p_file l_file
  tmp=$(mktemp)
  p_file=$(mktemp)
  l_file=$(mktemp)
  # shellcheck disable=SC2064 # 立即展开变量，期望如此
  trap "rm -f '$tmp' '$p_file' '$l_file'" RETURN

  # 父仓继承
  local parent_summary=""
  local inherits
  inherits=$(yq e '.inherits[0].path // ""' "$HARNESS_ROOT/manifest.yaml")
  if [ -n "$inherits" ] && [ -f "$HARNESS_ROOT/$inherits/manifest.yaml" ]; then
    parent_summary=$(generate_summary "$HARNESS_ROOT/$inherits/manifest.yaml" "")
  fi

  local local_summary
  local_summary=$(generate_summary "$HARNESS_ROOT/manifest.yaml" "")

  printf '%s\n' "$parent_summary" > "$p_file"
  printf '%s\n' "$local_summary" > "$l_file"

  awk -v start="$START_MARKER" -v end="$END_MARKER" \
      -v p_file="$p_file" -v l_file="$l_file" '
    function readfile(f,   line, content) {
      content = ""
      while ((getline line < f) > 0) content = content line "\n"
      close(f)
      return content
    }
    $0==start {
      print
      print "<!-- generated by sync-bridges.sh; do not edit between markers -->"
      print ""
      print "## Harness 加载顺序与摘要"
      print ""
      parent = readfile(p_file)
      if (parent != "\n" && parent != "") {
        print "### 父仓继承 rules"
        printf "%s", parent
        print ""
      }
      print "### 本仓 rules"
      printf "%s", readfile(l_file)
      in_gen=1; next
    }
    $0==end { in_gen=0 }
    !in_gen { print }
  ' "$bridge_file" > "$tmp"

  mv "$tmp" "$bridge_file"
  echo "✅ Synced $bridge_file"
}

# 遍历 bridges 列表
yq e '.bridges[] | .file' "$HARNESS_ROOT/manifest.yaml" | while read -r rel; do
  [ -z "$rel" ] && continue
  bridge="$HARNESS_ROOT/$rel"
  bake_bridge "$bridge"
done

# .cursorrules 走单独脚本
"$HARNESS_ROOT/scripts/generate-cursorrules.sh"
